### ISSUE TITLE
f1tenth Dockerfile

### ISSUE THREAD

**Issue by stevensantos2** [f1tenth/f1tenth_simulator#2]
what would i need to include in order to have a properly written docker file for running the f1tenth simulator? I would like to use the most updated version of the simulator which utilizes gazebo 9 and ubuntu 18.04.

**Comment by hzheng40** [comment]
I'm not sure if you're looking at the right simulator? This implementation does NOT use Gazebo.
We do have [this](https://github.com/f1tenth/f1tenth_gym_ros) which is containerized.

**Comment by stevensantos2** [comment]
Thank you for your response. I was wondering if the host OS needs to be ran on ubuntu, if so would i be able to run it in an ubuntu vm?
