### ISSUE TITLE
Unable to manually move car

### ISSUE THREAD

**Issue by stevensantos2** [f1tenth/f1tenth_simulator#3]
I just finished following the installation steps and currently have the simulator running fine. I am having trouble moving the car with WASD keys and I am wondering how I can fix that. I am running the simulator within an ubuntu vm and have had any other issues.

**Comment by hzheng40** [comment]
You'll have to keep the terminal that you're running the simulator focused, and then press 'k' to use the keyboard. Then you could use WASD while keeping the terminal focused.
